title: Simon Etter

email: simon0etter@gmail.com
github_username:  ettersi
office: S17-05-08

url: ettersi.github.com

keep_files: [linked,.git]

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # See https://jekyllrb.com/docs/troubleshooting/#configuration-problems

gems:
  - jekyll/scholar

scholar:
    source: .
    bibliography: _library.bib
    style: _layouts/bibliography.csl
    bibliography_template: bibliography

    bibtex_filters: braces
    sort_by: year, month
    order: descending
    bibliography_list_tag: ul
    reference_tagname: div
